version: '3'

services:

  discovery-service:
    image: aista/discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - 'eviction-interval-timer-in-ms: 1000'

  mysql-server:
    image: mysql:5.7
    container_name: mysql-server
    volumes:
      - mysql-data:/var/lib/mysql:rw
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'user_service'
      
  user-service:
    build: ./
    depends_on:
      - discovery-service
      - mysql-server
    container_name: user-service
    ports:
      - '8091:8080'

volumes:
   mysql-data:
   