version: '3'

services:

  discovery-service:
    build: ../discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - 'eviction-interval-timer-in-ms: 1000'

  mysqlserver:
    image: mysql:5.7
    container_name: mysqlserver
    volumes:
      - mysql-data:/var/lib/mysql:rw
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'user_service'
      
  # userservice:
   # build: ./
   # depends_on:
     # - discovery-service
     # - mysqlserver
   # container_name: userservice
   # ports:
     # - '8091:8080'
   # environment:
     # - 'DOCKER_MACHINE_IP:192.168.99.100'
     # - 'APP_PORT:8080'

volumes:
   mysql-data:
   