version: '3'

services:

  eureka-server:
    build: ../eureka/
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - 'eviction-interval-timer-in-ms: 1000'

  mysql-server:
    image: mysql:5.7
    container_name: mysql-server
    volumes:
      - /mysql-data:/var/lib/mysql:rw
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'user_service'
      
  microservice--user-service:
    build: ./
    depends_on:
      - eureka-server
      - mysql-server
    container_name: microservice--user-service
    ports:
      - '8091:8080'
