spring:
  profiles:
    active: development
---
spring:
  profiles: development
  
  datasource:
    url: jdbc:mysql://mysqlserver:3306/user_service
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.aitesting.microservices: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://discovery-service:8761/eureka/

server:
  contextPath:   /auth
  port: ${APP_PORT:8080}

---
spring:
  profiles: docker
  
  datasource:
    url: jdbc:mysql://mysqlserver:3306/user_service
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.aitesting.microservices: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://discovery-service:8761/eureka/

server:
  contextPath:   /auth
  port: ${APP_PORT:8080}

  
jpa:
  database: MYSQL
  hibernate:
    ddl-auto: validate
